export const skills=[
 {group:'Frontend',icon:'Layout',summary:'I build responsive, accessible interfaces that feel fast and natural on every device.',items:['React.js','JavaScript ES6+','HTML5','CSS3','Responsive Design','React Router']},
 {group:'Backend',icon:'Server',summary:'I create structured APIs and server-side logic that keep applications secure and dependable.',items:['Node.js','Express.js','REST APIs','Authentication','API Integration','Error Handling']},
 {group:'Database',icon:'Database',summary:'I model, store, and retrieve application data with scalable document-based architecture.',items:['MongoDB','Mongoose','Data Modeling','CRUD Operations','Validation','Query Design']},
 {group:'Tools & Workflow',icon:'GitBranch',summary:'I use modern developer tools to organize code, collaborate, test, and deploy efficiently.',items:['Git','GitHub','Vite','npm','Vercel','VS Code']}
];
export const projects=[
 {slug:'4cc-company-website',title:'4CC Company Website',category:'Company Website',year:'2026',repo:'https://github.com/abdisamad-guure/4cc-company-frontend',live:'https://4cc-company-frontend.vercel.app',theme:'yellow',stack:['JavaScript','Vite','HTML5','CSS3','Vercel'],summary:'A responsive company website frontend for 4CC, built with JavaScript and deployed through Vercel.',problem:'A company website needs to present its brand and information clearly, work smoothly on different devices, and remain easy to publish and maintain.',solution:'I built the 4CC frontend as a Vite-powered JavaScript application, organized its public assets and source code, and configured it for Vercel deployment and custom-domain support.',features:['Responsive frontend experience','Vite-based project structure','Organized public assets','Vercel deployment configuration','Custom-domain support','Search indexing metadata'],learning:'This project strengthened my experience delivering a production-oriented frontend: organizing a web application, preparing it for deployment, and supporting the details that help a business website reach its audience.'},
 {slug:'luminous-ecommerce',title:'Luminous E-commerce',category:'Frontend E-commerce Experience',year:'2026',repo:'https://github.com/abdisamad-guure/e-commerce',live:null,theme:'blue',stack:['HTML5','CSS3','Font Awesome'],summary:'A premium consumer-electronics storefront with curated categories, flagship devices, testimonials, newsletter conversion, and a complete multi-column footer.',problem:'Technology stores need to display a large catalog without making discovery feel complicated. Luminous organizes different product families into a clear visual journey that starts with the brand promise and ends with a strong conversion opportunity.',solution:'I designed a structured landing experience with a bold hero, category-based discovery, featured product cards, customer proof, an email subscription area, and supporting footer navigation.',features:['High-impact product hero','Four curated category panels','Flagship product showcase','Customer testimonial cards','Newsletter call-to-action','Complete commerce footer'],learning:'This project strengthened my understanding of page hierarchy, Flexbox layout, reusable content cards, visual contrast, and the structure of an e-commerce landing page.'},
 {slug:'javascript-fundamentals',title:'JavaScript Fundamentals',category:'Programming Practice',year:'2026',repo:'https://github.com/abdisamad-guure/javascript',live:'https://javascript-blush-tau.vercel.app',theme:'yellow',stack:['JavaScript','HTML5','Vercel'],summary:'A bilingual collection of executable JavaScript exercises covering variables, data types, arithmetic operators, value assignment, and console output.',problem:'A strong foundation in JavaScript requires more than memorizing syntax. Each concept needs a small example that can be executed, inspected, and explained in clear language.',solution:'I created a focused learning page combining Somali explanations with working JavaScript examples. The exercises make core language behavior visible through browser console output.',features:['var, let, and const examples','Common JavaScript data types','Arithmetic and modulus operations','String and number behavior','Console-based output','Live Vercel deployment'],learning:'The project helped reinforce the relationship between data types, operators, variable scope, and readable program output—the building blocks used in larger React and Node.js applications.'}
];
